version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomationPreprodProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_GitRuntimeAutomationPreprodProject
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: vidiDec8
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
