version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GitRuntimeAutomationPreprodProject
  gitServerName: siqagituser
  gitUrl: https://github.com/siqagituser/SIQA_GitRuntimeAutomationPreprodProject
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: vidiDec8
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
- name: WmJDBCAdapter
  wpmServer: https://packages.softwareag.com
  wpmRegistry: softwareag
services:
- serviceName: project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:Database_newacc
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:DBInsert
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeautomationpreprod.integrations:SIQAAdapterFlow
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeautomationpreprod.integrations:SIQA_E2E_Mon_Test
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:addInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: project.siqa_gitruntimeautomationpreprod.integrations:SIQA_ThirdPPEdgeFS
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:ComplexFS
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:Basic_Flow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.math:divideInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.math:subtractInts
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.math:multiplyIntList
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: Basics_1:mapservice
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Basics_1:TryCatch
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: Map_1:TestFlow
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: REST_1_1.CurrentDateAndTime:_get
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.string:objectToString
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.804
- serviceName: SOAP_1_1:showDateAndTime
  packages:
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections:DatabasenewAcc
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
- serviceName: project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.operations.actions:dbnew
  packages:
  - name: SIQA_GitRuntimeAutomationPreprodProject
    version: "1.0"
  - name: SIQA_OriginTest_OnPremAssets
    version: "1.0"
configurationVariables:
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.user
  : sa
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.user
  : sa
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionEnabled
  : "false"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.driverType
  : Progress速 DataDirect速
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.blockingTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.transactionType
  : LOCAL_TRANSACTION
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.databaseName
  : SIQACloud
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.poolable
  : "false"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.serverName
  : vmiboint01
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.trustStore
  : ""
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.expireTimeout
  : "1000"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.portNumber
  : "1433"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.startupRetryCount
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.minimumPoolSize
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionEnabled
  : "false"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionManagerSettings.maximumPoolSize
  : "10"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.heartBeatInterval
  : "0"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.datasourceClass
  : com.wm.dd.jdbcx.sqlserver.SQLServerDataSource
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.password
  : "{AES}aYrXC43dTWsDUHRWG5mhTA=="
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.dbType
  : MSSQL
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.keyStore
  : ""
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.password
  : "{AES}B2Xqma4Ost5nVUiXctJydQ=="
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.startupBackoffSecs
  : "10"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.serverName
  : vmibint01
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionManagerSettings.poolIncrementSize
  : "1"
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.Database_newacc.connectionSettings.networkProtocol
  : tcp
  ? artConnection.SIQA_GitRuntimeAutomationPreprodProject.project.siqa_gitruntimeautomationpreprod.WmJDBCAdapter.com_wm_adapter_wmjdbc_JDBCAdapter.connections.DatabasenewAcc.connectionSettings.otherProperties
  : loginTimeout=60;driverType=thin;
